package cn.yl.web.model;

import cn.yl.web.model.base.BaseBall;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ball extends BaseBall<Ball> {
	public static final Ball dao = new Ball();

	public int count(){
		Long count = Db.queryLong("select count(*) as num from r_ball");

		return count==null ? 0: Integer.parseInt(count.toString());
	}
}
