package cn.yl.web.model;

import cn.yl.web.model.base.BaseTest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Test extends BaseTest<Test> {
	public static final Test dao = new Test();
}
