package cn.yl.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBall<M extends BaseBall<M>> extends Model<M> implements IBean {

	public void setQh(java.lang.String qh) {
		set("qh", qh);
	}

	public java.lang.String getQh() {
		return get("qh");
	}

	public void setRed1(java.lang.String red1) {
		set("red1", red1);
	}

	public java.lang.String getRed1() {
		return get("red1");
	}

	public void setRed2(java.lang.String red2) {
		set("red2", red2);
	}

	public java.lang.String getRed2() {
		return get("red2");
	}

	public void setRed3(java.lang.String red3) {
		set("red3", red3);
	}

	public java.lang.String getRed3() {
		return get("red3");
	}

	public void setRed4(java.lang.String red4) {
		set("red4", red4);
	}

	public java.lang.String getRed4() {
		return get("red4");
	}

	public void setRed5(java.lang.String red5) {
		set("red5", red5);
	}

	public java.lang.String getRed5() {
		return get("red5");
	}

	public void setBlue(java.lang.String blue) {
		set("blue", blue);
	}

	public java.lang.String getBlue() {
		return get("blue");
	}

	public void setPrizes(java.lang.Integer prizes) {
		set("prizes", prizes);
	}

	public java.lang.Integer getPrizes() {
		return get("prizes");
	}

	public void setFirstnum(java.lang.Integer firstnum) {
		set("firstnum", firstnum);
	}

	public java.lang.Integer getFirstnum() {
		return get("firstnum");
	}

	public void setSecondnum(java.lang.Integer secondnum) {
		set("secondnum", secondnum);
	}

	public java.lang.Integer getSecondnum() {
		return get("secondnum");
	}

	public void setOpendate(java.sql.Date opendate) {
		set("opendate", opendate);
	}

	public java.sql.Date getOpendate() {
		return get("opendate");
	}

	public void setRed6(java.lang.String red6) {
		set("red6", red6);
	}

	public java.lang.String getRed6() {
		return get("red6");
	}

}
